### ISSUE TITLE
use vanilla ruby JSON serialization by default

### ISSUE THREAD

**Issue by kellyredding** [redding/qs#46]
We discussed not bringing in any extra dependencies.  Abstract the JSON serialization behind a common API.  Users can provide a custom serializer as needed.

**Comment by jcredding** [comment]
@kellyredding - I can't use JSON by default without using the JSON gem. They didn't add it to ruby's standard library till 1.9.

**Comment by kellyredding** [comment]
@jcredding we discussed just going ahead and expecting it and raising a sane `LoadError` if it can't be loaded (ie you are on 1.8).
