### ISSUE TITLE
better handling when `init` hasn't been called

### ISSUE THREAD

**Issue by kellyredding** [redding/qs#71]
Right now you can call "client" methods on the `Qs` ns and you will just get rando `nil` errors if you haven't previously initialized qs.  It would be nice to have a "null client" or something that if you called any of the ns methods would tell you you need to init qs.

**Comment by kellyredding** [comment]
@jcredding have we taken care of this already?  I feel like we have.

**Comment by jcredding** [comment]
@kellyredding - I don't think we have. The client on the qs main module doesn't look like its defaulted to a null client. This is still valid and would be a nice way to avoid confusion.
